services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omar.alhammadi
      POSTGRES_PASSWORD: drowssap
      POSTGRES_DB: pulsesurveyv2-db-1
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: